### ISSUE TITLE
ModuleNotFoundError: No module named 'board'. Maybe missing dependency?

### ISSUE THREAD

**Issue by boncey** [sighmon/enviroplus_exporter#16]
Hello.
I've been using the main fork of enviroplus_exporter for quite some time without any problems.

But I fancied playing around with your homekit-enviroplus project.
But when I ran your fork of enviroplus_exporter I hit this error.

```
./enviroplus_exporter.py
Traceback (most recent call last):
  File "./enviroplus_exporter.py", line 10, in <module>
    import board
ModuleNotFoundError: No module named 'board'
```

Is there a missing dependency perhaps?

Thanks,
Darren.

**Comment by boncey** [comment]
I commented out the board stuff (it seems to be related to a battery that I don't have).
I then got this error.

```
Traceback (most recent call last):
  File "./enviroplus_exporter.py", line 14, in <module>
    import SafecastPy
ModuleNotFoundError: No module named 'SafecastPy'
```

Maybe also a dependency issue?

**Comment by boncey** [comment]
I've now realised that homekit-enviroplus works fine with the main fork of enviroplus_exporter so I'm not using this fork anymore.

BTW, loving getting my Enviro stats into HomeKit, so thanks for the really cool project. 👍
